// Local-only profile. No account connection and no uploaded personal data.
(function(){try{
if(document.getElementById('aviProfileButton'))return;
const KEY='avi_local_profile_v1';let profile={name:'',photo:''};try{profile=Object.assign(profile,JSON.parse(localStorage.getItem(KEY)||'null'));}catch{}
if(!/^data:image\/(jpeg|png|webp);base64,/.test(profile.photo||''))profile.photo='';
const style=document.createElement('style');style.textContent=`
#view-listen>.largetitle{position:relative;padding-left:58px}
#aviProfileButton{position:absolute;left:0;top:50%;transform:translateY(-50%);width:42px;height:42px;border-radius:50%;background:var(--card2);color:var(--text);font-size:20px;border:1px solid #7775;overflow:hidden;display:grid;place-items:center}
.avi-avatar img{width:100%;height:100%;object-fit:cover}.avi-avatar{flex-shrink:0;display:grid;place-items:center;background:#858892;color:white;border-radius:50%;overflow:hidden}
#page-local-profile{z-index:90;background:var(--bg,#101014)}
#page-local-profile .profile-wrap{padding:22px 20px 115px;max-width:680px;margin:auto}
.profile-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}.profile-head h1{font-size:25px;margin:0}.profile-close{background:var(--card2);color:var(--text);border-radius:50%;width:40px;height:40px;font-size:25px}
.profile-card{background:var(--card,#1d1d22);border-radius:22px;padding:0 18px;margin:18px 0}.profile-identity{display:flex;align-items:center;gap:14px;padding:24px 0}.profile-identity .avi-avatar{width:64px;height:64px;font-size:28px}.profile-identity b{font-size:21px}.profile-sub,.profile-note{color:var(--muted,#999);font-size:14px;line-height:1.6}.profile-row{display:flex;width:100%;align-items:center;justify-content:space-between;padding:18px 0;border-bottom:1px solid #8883;text-align:right;background:transparent;color:var(--text);font-size:17px;gap:12px}.profile-row:last-child{border:0}.profile-row span:last-child{color:var(--accent,#fa2d55)}
.profile-edit{padding:18px 0}.profile-edit[hidden],.profile-detail[hidden]{display:none}.profile-edit label{display:block;margin:0 0 8px}.profile-edit input[type=text]{display:block;width:100%;box-sizing:border-box;background:var(--card2);color:var(--text);padding:12px;border:1px solid #8885;border-radius:10px;font:inherit;margin-bottom:12px}.profile-edit button{background:var(--card2);color:var(--text);padding:10px 14px;border-radius:10px;margin:5px}.profile-edit .profile-save{color:var(--accent,#fa2d55)}.profile-detail{line-height:1.7;padding:6px 0 18px}.profile-status{min-height:20px;font-size:14px;color:var(--muted,#999)}
@media(min-width:820px){#page-local-profile{right:232px;width:calc(100% - 232px)}}`;
document.head.append(style);
const button=document.createElement('button');button.id='aviProfileButton';button.className='avi-avatar';button.type='button';button.setAttribute('aria-label','הפרופיל שלי');document.querySelector('#view-listen>.largetitle').append(button);
const page=document.createElement('section');page.id='page-local-profile';page.className='page';page.dir='rtl';page.setAttribute('aria-label','הפרופיל שלי');
page.innerHTML=`<div class="ascroll"><div class="profile-wrap"><div class="profile-head"><h1>הפרופיל שלי</h1><button class="profile-close" aria-label="סגירת הפרופיל">×</button></div><div class="profile-card"><div class="profile-identity"><div class="avi-avatar"></div><div><b id="aviProfileName"></b><div class="profile-sub">פרופיל מקומי · Avi Music</div></div></div><button class="profile-row" id="aviProfileEdit"><span>עריכת שם ותמונה</span><span>‹</span></button><form class="profile-edit" hidden><label for="aviProfileInput">שם לתצוגה</label><input type="text" id="aviProfileInput" maxlength="60" autocomplete="nickname"><button type="button" id="aviProfilePhoto">בחירת תמונה</button><button type="button" id="aviProfileRemove">הסרת תמונה</button><button type="submit" class="profile-save">שמירה</button><div class="profile-status" role="status" aria-live="polite"></div></form></div><p class="profile-note">השם והתמונה נשמרים רק בדפדפן במכשיר הזה. הם לא נשלחים לאפל, לגוגל או לאנשים אחרים.</p><div class="profile-card" id="aviProfileLinks"></div><p class="profile-note">זהו פרופיל מקומי, לא התחברות לחשבון ולא נעילת אתר.</p></div></div>`;
document.body.append(page);const form=page.querySelector('form'),status=page.querySelector('.profile-status');let pendingPhoto=profile.photo;
function avatar(el){el.replaceChildren();if(profile.photo){const img=document.createElement('img');img.src=profile.photo;img.alt='';el.append(img);}else el.textContent=profile.name.trim().charAt(0)||'א';}
function paint(){avatar(button);avatar(page.querySelector('.profile-identity .avi-avatar'));document.getElementById('aviProfileName').textContent=profile.name||'הפרופיל שלי';}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(profile));paint();return true;}catch{status.textContent='לא ניתן לשמור כרגע במכשיר הזה.';return false;}}
button.onclick=()=>{paint();openPage(page.id);};page.querySelector('.profile-close').onclick=()=>{closePage(page.id);button.focus();};page.addEventListener('keydown',e=>{if(e.key==='Escape'){closePage(page.id);button.focus();}});
document.getElementById('aviProfileEdit').onclick=()=>{form.hidden=!form.hidden;if(!form.hidden){document.getElementById('aviProfileInput').value=profile.name;pendingPhoto=profile.photo;status.textContent='';document.getElementById('aviProfileInput').focus();}};
form.onsubmit=e=>{e.preventDefault();const prior=profile;profile={name:document.getElementById('aviProfileInput').value.trim().slice(0,60),photo:pendingPhoto};if(persist()){form.hidden=true;}else profile=prior;};
document.getElementById('aviProfileRemove').onclick=()=>{pendingPhoto='';status.textContent='התמונה תוסר לאחר שמירה.';};
document.getElementById('aviProfilePhoto').onclick=()=>{const pick=document.createElement('input');pick.type='file';pick.accept='image/jpeg,image/png,image/webp';pick.onchange=()=>{const file=pick.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){status.textContent='בחר תמונת JPG, PNG או WebP עד 10 MB.';return;}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=c.height=192;const ctx=c.getContext('2d'),size=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-size)/2,(img.height-size)/2,size,size,0,0,192,192);pendingPhoto=c.toDataURL('image/jpeg',.82);status.textContent='התמונה מוכנה. לחץ שמירה.';}catch{status.textContent='לא ניתן לקרוא את התמונה.';}finally{URL.revokeObjectURL(url);}};img.onerror=()=>{URL.revokeObjectURL(url);status.textContent='לא ניתן לקרוא את התמונה.';};img.src=url;};pick.click();};
const links=document.getElementById('aviProfileLinks');function row(label,fn){const b=document.createElement('button');b.className='profile-row';const title=document.createElement('span'),chevron=document.createElement('span');title.textContent=label;chevron.textContent='‹';b.append(title,chevron);b.onclick=fn;links.append(b);}
if(typeof openMonthlyListening==='function')row('ההאזנה שלך',()=>{closePage(page.id);openMonthlyListening();});
row('הושמעו לאחרונה',()=>{closePage(page.id);openRecent();});
if(document.getElementById('page-apple-import'))row('ייבוא וטעם מוזיקלי',()=>{closePage(page.id);const b=[...document.querySelectorAll('#libRows button')].find(b=>b.textContent==='ייבוא וטעם מוזיקלי');if(b)b.click();else openPage('page-apple-import');});
row('פרטיות ושמירה במכשיר',()=>{detail.hidden=!detail.hidden;});const detail=document.createElement('div');detail.className='profile-detail';detail.hidden=true;detail.textContent='הפרופיל, הספרייה וההיסטוריה נשמרים בדפדפן במכשיר הזה. ניקוי נתוני האתר עלול למחוק אותם. נתונים אלה אינם מסתנכרנים בין מכשירים. בקשות חיפוש ונגינה פונות למקורות המוזיקה. פרופיל מקומי אינו הופך את האתר לפרטי ואינו מגן על הגישה אליו.';links.append(detail);paint();
}catch(e){console.warn('local-profile disabled',e);}})();
